Media queries
mikke89/RmlUi pull request #169
Opened 2021-01-26 10:14 UTC by Dakror

This is a big one. 

This PR adds support for basic media queries in RCSS.

# Usage & Features

- RCSS media-blocks to apply properties conditional to context properties:
  - viewport width & height given in pixels, supports range (min-/max-)
  - resolution, aka dpi (using the density_independent_pixel_ratio value), supports range (min-/max-)
  - aspect ratio, using ratio notation like `16/9`, internally using it as a float, supports range (min-/max-)
  - orientation "landscape" / "portrait", comparing viewport width against height
- Creating composite queries using "and" operator

Example usage:

```css
div {
	height: 48px;
	width: 48px;
}

@media (min-width: 640px) {
	div {
		height: 32px;
		width: 32px;
	}
}

@media (orientation: landscape) and (min-resolution: 90dpi) {
	div {
		height: 32px;
		width: 32px;
	}
}

@media (max-aspect-ratio: 4/3) {
	div {
		height: 64px;
		width: 64px;
	}
}
```

----

I've tried to adhere as closely as possible to the early CSS media query standards, by for instance inforcing fixed units like dpi for resolution, and pixels for width & height and reusing the CSS names for the various properties. The CSS feature of media distinction like "screen" etc. does not really apply in RCSS, therefore it was omitted. The current approach matches media blocks with an all or nothing approach, since only conjunctive chaining ("and") is allowed.

# Internals

In order to assemble the correct style sheet for a given context configuration, a new top-level class above `StyleSheet` was introduced: the `StyleSheetContainer`. It maps a `PropertyDictionary` of the query-list properties to the contained sub-stylesheet.

A function `UpdateMediaFeatures` creates a new combined `StyleSheet` and stores it inside the container, giving external access through a non-owning pointer.

For parsing, new parsers needed to be introduced, namely for the aspect ratio notation, and others for the unit enforcing.

The style sheet parser received a new parsing method with its own state machine parsing the custom syntax of the media query list

The document re-compiles the stylesheet when it detects a context property change.

A unit test suite checking all properties is provided.

2021-01-26 14:30 UTC, Dakror commented
Hey @mikke89 can you tell me why the `context` parameter inside `Factory::InstanceDocumentStream` for the element instantiation is nullptr? If i pass the context that the method is receiving anyway, no issue seems apparent but i resolve the additional error that i reported in #170 regarding the missing sprites

2021-01-26 15:41 UTC, Dakror commented
The issue with #170 and this, is that we need the context in the tmp document to compile a stylesheet.. what to do though..

2021-01-26 16:18 UTC, mikke89 commented
First of all, awesome and great work! You're learning the library fast :)
It's great to have this feature, I know other user have requested it as well.

I'll go through it in more detail later on.

> Hey @mikke89 can you tell me why the `context` parameter inside `ReloadStyleSheet` for `InstanceDocumentStream` is nullptr? 

Yeah, the main reason for this is that I wanted to ensure that the state of the current context is not changed when `ReloadStyleSheet` occurs. This can happen due to eg. events, and any state change from this function would be quite unexpected. Is there still an issue here after #171?

2021-01-26 16:27 UTC, Dakror commented
Yeah since we can't compile the stylesheet in the context-less temporary document, some warnings arise, particularly when images look for sprites (found it in my game as a test case :D ) . While these warnings don't cause any real problem since only the stylesheetcontainer is used from the temporary document, we still need to quench those warnings somehow..

2021-01-26 19:10 UTC, mikke89 commented
Oh, I see. I'll have to think about that some more.

2021-01-31 22:03 UTC, mikke89 requested changes
I've taken a detailed look at this now. Thanks a lot, looking forward to merging this :) I'm also pleased to see the very nice PR description.

Please see the detailed review comments, as well as the following remarks.

- The dpi unit for resolution doesn't really make sense as dpi vs pixels are fixed in RmlUi. The unit is actually more like the CSS `dppx` (dots per pixel), but this also doesn't make sense in RmlUi, because one dot is always one pixel. What we really want is dp-ratio `dpr`, but this again may be confusing to someone coming from CSS. However, I see that CSS adds an `x` unit alias, and this unit would actually also make sense for us. So I suggest that we call it that. More long-term, we might consider adopting the CSS approach to pixels, so that one RCSS pixel can be scaled relative to device pixels.

- I can see several RCSS problems introduced with this change. Eg. the 'demo' sample is not able to override the 'max-width' property. The VisualTests demo looks very broken. For some strange reaon, warnings are often given when tables are present, see eg. `table_01` in VisualTests. Some of these problems may be due to specificity, eg. make sure all the rules are applied in the order they appear. Would be nice to have some unit tests for this.

- There is a substantial performance regression when loading documents, more than double the loading time compared to master. Haven't looked into it in any more detail, but we need to figure this out, it should not be measurably slower when not using media queries. I suspect there is a lot of duplicate work going on, the merging in particular should be looked at.


Here are some more notes for future changes. We can merge this PR before we work on any of this, but leaving these notes here for now.

- Need to test keyframes and sprite sheets in media block. I suspect eg. sprites won't properly updated as is. Any element/function that uses Element::GetStyleSheet should be investigated in particular.

- Other logic operations: Comma (OR), not... Maybe Media Queries level 4 syntax eg. `(100px < width <= 1200px)`? If we do implement that, then we may discard the `min/max-width` properties as the other operators are so much nicer.

- Instead of dirtying style sheets and definitions every time context dimensions and dp-ratio change, add flags to style sheet containers that tell whether they need to be dirtied when that value changes. So that we don't need to do anything if media queries are not used.

2021-02-01 06:59 UTC, Dakror commented on Include/RmlUi/Core/ID.h
> +	AspectRatio,
This is an understatement, because we can't use PropertyDictionary or any of the property parsing code unless we template it or something.

2021-02-01 11:30 UTC, mikke89 commented on Include/RmlUi/Core/ID.h
> +	AspectRatio,
All we need is some sprinkling of `static_cast<PropertyId>(MediaQueryId::Width)`. Or create a small helper function to make it a bit shorter: `CastId(MediaQueryId::Width)`.

2021-02-01 11:32 UTC, Dakror commented on Include/RmlUi/Core/ID.h
> +	AspectRatio,
uhh so we just recycle it, ignoring what the original property id would be? okay :shrug:

2021-02-01 11:40 UTC, mikke89 commented on Include/RmlUi/Core/ID.h
> +	AspectRatio,
Exactly, this is an entirely separate thing, we just happen to parse them similarly. The PropertyId refers to the normal style sheet properties and their specification. Other specifications use other values instead of the PropertyId enums. It is the same situation for eg. decorator properties. It would be a bit cleaner if we could define an implicit conversion from one enum class to another, but that is not possible.

2021-02-01 11:42 UTC, Dakror commented on Include/RmlUi/Core/ID.h
> +	AspectRatio,
Okay i see

2021-02-01 11:42 UTC, Dakror commented on Include/RmlUi/Core/ID.h
> +	AspectRatio,
Okay i see

2021-02-01 17:05 UTC, Dakror commented on Source/Core/Elements/ElementImage.cpp
> +			if (auto style_sheet = document->GetStyleSheet())
pretty sure you meant const StyleSheet*

2021-02-01 17:06 UTC, mikke89 commented on Source/Core/Elements/ElementImage.cpp
> +			if (auto style_sheet = document->GetStyleSheet())
Yes :)

2021-02-01 17:10 UTC, Dakror commented on Source/Core/StyleSheetParser.cpp
>  void StyleSheetParser::Shutdown()
it doesnt need any shutdown...?

2021-02-01 17:43 UTC, mikke89 commented on Source/Core/StyleSheetParser.cpp
>  void StyleSheetParser::Shutdown()
A reset I mean, like the other parser to clear memory and old references.

2021-02-01 19:16 UTC, Dakror commented on Include/RmlUi/Core/Property.h
> +		DPI = 1 << 9,               // dots per inch, density resolution; number suffixed by 'dpi'; fetch as < float >
I really dont see the point in this renaming, DPI is so much more sensible than a ambiguous "x" unit. Also i don't agree that dpi is always fixed, its by definition the value that the library currently calls the density_independent_pixel ratio and on most platforms and frameworks this is called DPI or density. But ultimately its your call.

2021-02-02 06:26 UTC, Dakror commented
Visual tests are fixed in 98bcc50

2021-02-02 06:48 UTC, Dakror commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
This is only needed in the parsing logic, because now the stylesheet doesn't construct itself anymore. Without this the parsing function gets a lot uglier because instead of using MediaBlock structs for the current block i'd need to track all the components of a stylesheet individually to then ultimately call the constructor with all the parts... this feels very ugly to me.

2021-02-02 06:50 UTC, Dakror commented
Do you have any heavy hitting test for the performance issues you mentioned? I can't seem to detect a noticeable difference, looking for instance at unit test run duration.

2021-02-02 17:59 UTC, mikke89 commented on Include/RmlUi/Core/Property.h
> +		DPI = 1 << 9,               // dots per inch, density resolution; number suffixed by 'dpi'; fetch as < float >
DPI (dots per inch) means something completely different from dp-ratio. DPI values are on the order of 100, while dp-ratio would usually be 1-2. Which I believe would be quite confusing. If we implement the `x` unit, that would mean the same in CSS and RCSS, so I believe we should go that route. I kind of like x too, it's a normal unit for a factor.

2021-02-02 18:00 UTC, Dakror commented on Include/RmlUi/Core/Property.h
> +		DPI = 1 << 9,               // dots per inch, density resolution; number suffixed by 'dpi'; fetch as < float >
okay

2021-02-02 18:01 UTC, mikke89 commented
> Do you have any heavy hitting test for the performance issues you mentioned? I can't seem to detect a noticeable difference, looking for instance at unit test run duration.

Yeah, if you run the `benchmarks` sample, take a look at the ElementDocument:LoadDocument benchmark, that is what I used.

2021-02-02 19:51 UTC, Dakror commented
I've investigated the performance increase, and it purely stems from the heavy hitting DirtyDefinition call in SetStyleSheetContainer upon ProcessHeader call in ElementDocument. This adds a solid 5-10ms where normally only 5ms total were needed (on my system). Mitigating this would require adding all the relevant flags for invalidating only what's necessary and i think this is beyond me or this PR.

2021-02-02 23:24 UTC, mikke89 commented
Alright, thanks for looking into it. As long as we can fix the performance later on, I'm good with it for now.

2021-02-02 23:39 UTC, mikke89 commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
I see. Could we perhaps make the constructor private? That way it is clear that the parser takes control of construction.

2021-02-05 15:01 UTC, Dakror commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
Private constructor doesn't solve that though? or do you mean private constructor + friend def?

2021-02-05 15:25 UTC, Dakror commented
Working on a unit test i discovered that yeah indeed sprite updates are not updated, specifically i tested wether an ElementImage would update, but there is no method reacting to a change of that sort in that class. What do you think is the best approach to notify every element of relevant changes of this sort? I feel like this PR is getting a bit too big...

2021-02-05 15:26 UTC, Dakror commented
I would say sprites + keyframes get a second PR?

2021-02-05 16:27 UTC, mikke89 commented
Yeah, I had the same issue in the high_dpi branch, which is why I expected it here as well. I had it half-working there, but now that we have media queries we probably want to make changes to the approach taken there.

Anyway, I'm fine with leaving that part out of this PR, we can work on that later.

2021-02-05 17:38 UTC, Dakror commented on Source/Core/StyleSheetContainer.cpp
> +    compiled_style_sheet = std::move(new_sheet);
As discussed below this will / should be tackled in a separate PR

2021-02-06 17:02 UTC, mikke89 commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
Right, I meant private + friend.

2021-02-06 17:03 UTC, Dakror commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
ah okay

2021-02-06 17:07 UTC, Dakror commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
Private constructor does not work, it complains about the unique_ptr creations.

2021-02-06 17:14 UTC, mikke89 commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
Oh right, you can try to use `auto x = UniquePtr<...>(new StyleSheet());` instead of MakeUnique.

2021-02-06 17:20 UTC, Dakror commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
Argh damn, another issue is CombineStyleSheetContainer where i need to clone stylesheets (since i don't want to move them off of the incoming container) and was using CombineStyleSheet with an empty stylesheet.

2021-02-06 17:26 UTC, mikke89 commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
Oh I see, maybe allow passing a nullptr and handle it that way? Maybe there is a more efficient way to do it entirely?

2021-02-06 18:11 UTC, Dakror commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
i would need to add the container as a friend too to solve it, since it creates the compiled stylesheet...

2021-02-06 18:13 UTC, mikke89 commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
Alright, I'll let you deal with it how you like, if this gets too complicated then just drop it :)

2021-02-06 18:14 UTC, Dakror commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
oki!

2021-02-06 18:15 UTC, Dakror commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
It's always the small things haha

2021-02-06 18:19 UTC, mikke89 commented on Include/RmlUi/Core/StyleSheet.h
> +	friend StyleSheetParser;
Haha, yes, it's not a big thing. Some times it's easy to get lost in the details. :P

2021-02-07 00:31 UTC, mikke89 reviewed
Thanks, looking good, just a few minor comments here.

So, after we merge this PR, we have the following high priority things to solve:

- The lifetime issue / potential crashes [described here](https://github.com/mikke89/RmlUi/pull/169#discussion_r567480635).
- The performance regression when loading documents.

I consider these two issues release blocking.

Additional things to work on, but lower priority (taken from [previous post](https://github.com/mikke89/RmlUi/pull/169#pullrequestreview-579894820)).

- Support for keyframes and sprite sheets.
- Expanded query syntax.
- Dirty flags.

2021-02-07 00:31 UTC, mikke89 commented on Source/Core/StyleSheetParser.h
> +using MediaBlockListRaw = Vector<MediaBlock>;
```suggestion
using MediaBlockList = Vector<MediaBlock>;
```
The raw suffix on the previous type actually referred to the contained raw pointer, since StyleSheetNodeList is already used as container of unique pointers. That's not the case here, so we can drop that suffix. Totally understand the confusion here though :)

2021-02-07 00:31 UTC, mikke89 commented on Source/Core/StyleSheetSpecification.cpp
> +	RMLUI_ASSERTMSG(instance->properties.shorthand_map->AssertAllInserted(ShorthandId::NumDefinedIds), "Missing specification for one or more Shorthand IDs.");RMLUI_ASSERTMSG(instance->properties.proper
Maybe add back the newline as well :)

2021-02-07 00:31 UTC, mikke89 commented on Source/Core/PropertyParserRatio.h
> +#define RMLUI_CORE_PropertyParserRatio_H
```suggestion
#ifndef RMLUI_CORE_PROPERTYPARSERRATIO_H
#define RMLUI_CORE_PROPERTYPARSERRATIO_H
```

2021-02-07 09:12 UTC, Dakror commented
From my point of view, these issues would all be solvable using dirty flags because:
- Performance regression comes from the blunt `DirtyDefinition` which is super expensive
- Sprites and Keyframes aren't properly invalidated currently anyway

2021-02-07 17:54 UTC, mikke89 approved these changes

2021-02-07 17:59 UTC, mikke89 commented
Yeah, dirty flags sounds like a good idea. I had a closer look at the lifetime issue, and it looks like we're not storing any related references around from the style sheet. So it should be all good, at least for now, and I feel a lot more comfortable merging it as is. But we should try to make it future proof as well.

Thank you for the hard work, cheers!

2021-02-07 18:01 UTC, merged