Fixed a rounding error in the border radius color lerp
mikke89/RmlUi pull request #203
Opened 2021-07-09 15:51 UTC by jac8888

The lerp on the colors in the border radius code sometimes had an error that happened because the result was truncated instead of rounded.

It could be seen when blending two colors that were the same. The points along the arc would have different colors, like this:
```
DEBUG: color is 255, 224, 102
DEBUG: color is 255, 223, 101
DEBUG: color is 255, 223, 101
DEBUG: color is 254, 223, 101
DEBUG: color is 254, 223, 101
DEBUG: color is 255, 224, 102
DEBUG: color is 255, 224, 102
```

This is what this behavior would look like:
![qwerty](https://user-images.githubusercontent.com/78047391/125102601-b3230680-e098-11eb-9cf0-4bdcdd80fc91.png)

I didn't modify the lerp function itself. I only changed the way it is called in this specific case. There may be other places where a similar fix is needed.

2021-07-09 18:54 UTC, mikke89 requested changes
Thanks a lot for contributing back to the project!

Could you use `Math::RoundToInteger` instead? Then you can also drop the math.h header.

I think long-term we might want to make an overload in lerp for Colourb, but this is alright for now. I think we also have a color interpolation function in the animation system which properly interpolates in linear color space. That one might be the correct one to use here as well.

2021-07-09 23:11 UTC, jac8888 commented
Thank you for maintaining the project!

Absolutely, for now I've made only the change to the rounding function.

I found the code you were talking about in the ElementAnimation. I hadn't even considered the color space. I can do some more testing with the rounding on it next week and see if it will be good to use here as well.

2021-07-10 11:12 UTC, mikke89 approved these changes

2021-07-10 11:13 UTC, mikke89 commented
Thank you, sounds good! I'll merge this in the meantime.

2021-07-10 11:14 UTC, merged