Upgraded font-weight
mikke89/RmlUi pull request #296
Opened 2022-04-06 23:21 UTC by MexUK

This PR upgrades support for font-weight in .rcss files:

font-weight: (uint:0-0xFFFF)
and
font-weight: thin|light|normal|medium|bold|black

The PR supports 2 ways to load weights for fonts:

Rml::LoadFontFace("assets/OpenSans.ttf", false, 300); // Only load weight 300 from this font file.
or
Rml::LoadFontFace("assets/OpenSans.ttf", false); // Load all weights from this font file. (The third arg defaults to 0).

The PR also tries to match faces by the nearest weight, after trying to match by a direct weight.

![font-weights](https://user-images.githubusercontent.com/2442591/162085855-87037416-18df-4cdc-a7f6-10cbc9b18dd8.png)

2022-04-07 13:17 UTC, mikke89 requested changes
Thank you! This is awesome, a very welcome addition.

I have some suggestions here after looking over it, let me know what you think.

Haven't tested it properly yet, I see the PR is failing many of the unit tests. Let me know if I can be of help for fixing them.

2022-04-07 13:17 UTC, mikke89 commented on Source/Core/StyleSheetSpecification.cpp
> +	RegisterProperty(PropertyId::FontWeight, "font-weight", "400", true, true).AddParser("font_weight");
```suggestion
	RegisterProperty(PropertyId::FontWeight, "font-weight", "normal", true, true).AddParser("font_weight");
```

2022-04-07 16:58 UTC, MexUK commented on Include/RmlUi/Core/Core.h
>  /// @param[in] fallback_face True to use this font face for unknown characters in other font faces.
Sounds good. Maybe weight_to_load for loading and weight_to_match for lookup?

2022-04-07 16:59 UTC, MexUK commented on Source/Core/FontEngineDefault/FreeTypeInterface.cpp
> +		case 0x4A1414A: // wght
I'm not sure about endianess issues, but I think the 2 hex values I put are incorrect.
It should be 0x77676874 for wght and 0x77647468 for wdth.

2022-04-07 17:00 UTC, MexUK commented on Source/Core/FontEngineDefault/FontFamily.cpp
> +
For sure.

2022-04-07 18:24 UTC, MexUK commented
I've made a commit with the requested code changes.
I'll try and look into the unit tests soon.
If anything else needs changing, just let me know.

2022-04-10 16:58 UTC, mikke89 commented on Source/Core/LayoutInlineBoxText.cpp
> +	if ((int)weight > 0)
weight != ::Auto?

2022-04-10 16:58 UTC, mikke89 commented on Source/Core/LayoutInlineBoxText.cpp
> +	if ((int)weight > 0)
weight != ::Auto?

2022-04-10 17:29 UTC, mikke89 commented on Include/RmlUi/Core/Core.h
>  /// @param[in] fallback_face True to use this font face for unknown characters in other font faces.
Alright, `weight_to_load` looks good to me.

Although instead of `weight_to_match` I would actually prefer just `weight`, since there it is used just like the `style` parameter. So they should look the same way as each other, and I think 'match' is already understood here.

Also, could you add the `weight_to_load` parameter to the parameter list just above?

Eg:
```
/// @param[in] weight_to_load The weight to load when the font face contains multiple weights.
```

2022-04-10 17:29 UTC, mikke89 commented on Include/RmlUi/Core/Core.h
>  /// @param[in] fallback_face True to use this font face for unknown characters in other font faces.
Adjust the `weight` parameter comment like above.

2022-04-10 17:43 UTC, mikke89 reviewed
Thanks for continuing to work on this!

Can I ask about some use cases:
- How do we handle the case when the font face does not contain the desired weight? Do we load it at all?
- If we still load it, what should the font weight be registered as?

2022-04-10 17:43 UTC, mikke89 commented on Include/RmlUi/Core/FontEngineInterface.h
> +	virtual bool LoadFontFace(const String& file_name, bool fallback_face, Style::FontWeight weight_to_load);
Adjust the `weight` parameter comment like above.

2022-04-10 17:43 UTC, mikke89 commented on Include/RmlUi/Core/FontEngineInterface.h
> +	virtual bool LoadFontFace(const byte* data, int data_size, const String& family, Style::FontStyle style, Style::FontWeight weight_to_load, bool fallback_face);
Adjust the `weight` parameter comment like above.

2022-04-10 17:50 UTC, mikke89 commented on Source/Core/FontEngineDefault/FreeTypeInterface.h
> +bool GetFaceAxisData(const byte* data, int data_length, std::vector<FreeType::FaceAxisData>& weightsAndWidths);
```suggestion
bool GetFaceAxisData(const byte* data, int data_length, Vector<FreeType::FaceAxisData>& weightsAndWidths);
```

2022-04-11 00:41 UTC, MexUK commented on Include/RmlUi/Core/FontEngineInterface.h
> +	virtual bool LoadFontFace(const String& file_name, bool fallback_face, Style::FontWeight weight_to_load);
Currently it's implemented like so:
When loading a font (in c++) and the requested weight isn't found, FreeType::LoadFace(..) will return 0 and the face/weight isn't registered, resulting in the message "Failed to load font face ..".
When using a font (in .rcss) and the requested weight isn't loaded, it will use the nearest loaded face/weight for that loaded font.

2022-04-11 08:53 UTC, mikke89 commented on Include/RmlUi/Core/FontEngineInterface.h
> +	virtual bool LoadFontFace(const String& file_name, bool fallback_face, Style::FontWeight weight_to_load);
Great, that sounds like the right approach to me!

2022-04-11 12:34 UTC, mikke89 reviewed
I tested this PR more thoroughly now. Appreciate your continued work on this! Sorry about my reviews coming a bit in chunks, I have gone over everything now though. 

Currently, the samples don't open correctly since all included fonts fail to load. It seems to fail whenever the font file does not provide anything for `FT_Get_MM_Var`, which seems common for all single-weight fonts. A quick fix is to continue after `GetFaceInstanceIndexForWeight` regardless, when the weight is auto. However, this is not sufficient for all cases. See the following test code for loading fonts in the sample shell:

```cpp
void Shell::LoadFonts(const char* directory)
{
	using Rml::Style::FontWeight;
	
	struct FontFace {
		Rml::String filename;
		bool fallback_face;
		FontWeight weight;
	};
	FontFace font_faces[] = {
		{ "OpenSans-VariableWidth.ttf",    false, FontWeight::Auto },  // Loads weights [300, 400, 600, 700, 800, 300, 400, 600, 700, 800] (loads faces twice!)
		{ "OpenSans-VariableWidth.ttf",    false, FontWeight(800) },   // Loads 800 (correct)
		{ "OpenSans-VariableWidth.ttf",    false, FontWeight::Light }, // Loads 300 (correct)
		
		{ "OpenSans-Regular.ttf",    false,   FontWeight::Auto }, // Fails to load, with basic fix it loads as 400 (correct)
		{ "OpenSans-Bold.ttf",       false,   FontWeight::Auto }, // Fails to load, with basic fix it loads as 700 (correct)
		{ "OpenSans-ExtraBold.ttf",  false,   FontWeight::Auto }, // Fails to load, with basic fix it loads as 400 (wrong)
		{ "OpenSans-Light.ttf",      false,   FontWeight::Auto }, // Fails to load, with basic fix it loads as 400 (wrong)
		
		{ "OpenSans-Regular.ttf",    false,   FontWeight::Normal }, // Fails to load (ideally this would load correctly and be registered as 400)
		{ "OpenSans-Bold.ttf",       false,   FontWeight::Bold },   // Fails to load (ideally this would load correctly and be registered as 700)
		{ "OpenSans-ExtraBold.ttf",  false,   FontWeight::Bold },   // Fails to load (ideally this would load correctly and be registered as 700)
		{ "OpenSans-ExtraBold.ttf",  false,   FontWeight::Black },  // Fails to load (ideally this would load correctly and be registered as 900)
		
		{ "LatoLatin-Regular.ttf",    false, FontWeight::Auto }, // Fails to load, with basic fix it loads as 400 (correct)
		{ "LatoLatin-Italic.ttf",     false, FontWeight::Auto }, // Fails to load, with basic fix it loads as 400 (correct)
		{ "LatoLatin-Bold.ttf",       false, FontWeight::Auto }, // Fails to load, with basic fix it loads as 700 (correct)
		{ "LatoLatin-BoldItalic.ttf", false, FontWeight::Auto }, // Fails to load, with basic fix it loads as 700 (correct)
		{ "NotoEmoji-Regular.ttf",    true , FontWeight::Auto }, // Fails to load, with basic fix it loads as 400 (correct)
	};

	for (const FontFace& face : font_faces)
	{
		Rml::LoadFontFace(Rml::String(directory) + face.filename, face.fallback_face, face.weight);
	}
}
```

What we want is the ability to override the font weight if it registers as the wrong one. 

Thus, I propose this functionality for the `weight_to_load` parameter:
- If the font provides multiple font weights, then the weight parameter works like now: Loads only the appropriate weight and fails if it cannot be found.
- On the other hand, if the font face contains only a single face (whether or not it provides `MM_var`), then the weight parameter overrides whatever is auto-detected.
- This would also ensure backward compatibility, currently it fails loading the debugger plugin for this reason.

If you agree, we should probably change the `weight_to_load` parameter back to `weight` again, since it now has two meanings, one of them not having anything to do with loading. This behavior should be noted in the function calls in `Core.h` .

2022-04-11 12:34 UTC, mikke89 commented on Source/Core/FontEngineDefault/FontProvider.cpp
> +				if (Get().LoadFontFace(buffer, (int)length, fallback_face, std::move(buffer_ptr), file_name, {}, Style::FontStyle::Normal, axis_data[i].weight))
There is an issue here with the ownership and lifetime of the buffer_ptr. This memory needs to outlive all faces using this memory, until they have all called `FreeType::ReleaseFace`. Currently, the first font face loaded here will own the memory for all of them.

For this to be correct, we need to consider the destruction of the `FontFamily`'s font_faces. We don't have any guarantees about the order of destruction here, so currently we risk use-after free and undefined behavior (if the first font face is destroyed first).

One possible solution is to move out all the owning memory into a separate list in the FontFamily, and make sure that one is destroyed *after* the destruction of `font_faces`.

2022-04-11 12:34 UTC, mikke89 commented on Source/Core/FontEngineDefault/FontProvider.cpp
> +			return false;
Log an error message.

2022-05-01 12:17 UTC, mikke89 commented
Hey. I'm just wondering if you intend to keep working on this PR? We are getting close now, but otherwise I can offer to fix up the last bits so we can get it merged. Cheers!

2022-05-02 23:06 UTC, MexUK commented
Hey, apologies for not finishing the code changes, I've been very busy recently. Thanks for offering to finish them, that would be awesome if you could.

2022-05-09 12:40 UTC, mikke89 approved these changes

2022-05-09 13:54 UTC, merged