Vulkan
mikke89/RmlUi pull request #328
Opened 2022-06-22 07:21 UTC by wh1t3lord

We are really close to finish this GAPI implementation! 

Current state is:

- [x] General implementation (rendering, initialization, destroying, etc);
- [ ] Implement static resources;
- [ ] Improve performance, because current implementation of RenderCompiledGeometry works slower than OpenGL versions.

2022-06-22 21:23 UTC, mikke89 commented
Thanks for continuing this work!

I think we also need to figure out what to do with textures. Currently they are not released until shutdown really. This causes trouble with e.g. the lottie sample which crashes after a few seconds since that one keeps generating new textures in a loop. This could in principle also be a problem when using a lot of different font styles, as that would also generate a lot of textures.

2022-06-25 18:50 UTC, wh1t3lord commented
"Implemented" static resources. 

But there is a one thing... Still we have new and delete operations that will cause by containers. I minimized and used all things in fixed-size manner (like we developed for emdedded devices, IMO it is just a good approach for developing things on C++), but std doesn't provide a good solution for creating std::queue with fixed-size. 

As possible solution is to use boost::circular_buffer for replacing std::deque, but still it is not a sane variant, because we don't need to use boost for library. 

To sum up, all things like buffer handling, handling on cpu side data (like Rml::Containers) all goes with fixed-size manner and it is really good, because we removed all explicit new and delete operations at all. But still it is reasonable to achieve full pre-allocated behavior for all system (renderer at least, so what I did now). 

I don't call for implement that for internal stuff, like how you manage your resources for UI elements and how it calculates, but still it would be a great achievement in UI development for C++. The library just uses only static, pre-allocated resources for everything, looks like 90s where you have only fixed, limited memory and you need to survive somehow and for user it is great to specify how many real memory he needs for executing his application.

Anyway, there's one thing to deal with it is to understand why invaders don't work, and why the transform example has strange execution of animation (?), because when I use fast move slider animation plays, but if I stop the picture freezing.

I don't understand why, but RenderDoc probably will say to me what's wrong. I hope there's no GL code or something else in animation implementation, because it can interrupt Vulkan execution.

Hope to finish this until next weekends.

2022-06-25 23:09 UTC, mikke89 commented
I see that animations are working now too, good job!

In my view it is more important in a sample renderer like this that the code is easily understandable, rather than trying to come up with clever (CPU-side) memory allocation techniques. Users that care a lot about memory allocation will mostly likely have their own memory pools they want to integrate the renderer into in this case. As you say there are no great standard libraries for these things, so I'd prefer we just used `std::vector`, or new/delete when you need pointer stability. At least until profiling shows significant performance overhead.

Furthermore, rather than having a fixed upper limit on resources I think we should rather allocate new resources as required. I believe a sample renderer should be general enough to work in all situations. If users want to cap resources for their situation that is fine and they can do that with their own modifications.

Keep up the good work :)

2022-06-26 09:00 UTC, wh1t3lord commented
@mikke89 

It's actually good to have two implementations. One "naive" one that shows extremely simple resource management logic (using your OpenGL as an example) and on the other side to have an implementation that is not simple. And this is important, because most users will expect a "perfect" implementation that will immediately be both super-optimized and generally that everything will work well, but in most cases, no one of course obliges us to make examples of integrations at a very high level. Because everything is learned by comparison, for us, if we really develop as if we were doing it for embedded devices, then it's just a plus for us, nothing more.

I wanted to show the users how you could develop your Vulcan renderer in the best way, and give the basic ideas, which are laid down in the implementation, though the standard library does not allow to achieve what I wanted from the CPU, and it's a pity.

2022-06-28 13:56 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +			delete p_texture;
This is problematic because it duplicates release responsibility together with `m_queue_pending_for_deletion_textures`. All textures should have received a call to `ReleaseTexture` before we get here, so m_textures should be empty at this point too.

In fact, we can remove m_textures entirely, it has no purpose anymore. Just queue the textures for deletion during the call to `ReleaseTexture` and release the queued textures as normal here.

2022-06-28 13:59 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.h
> +	Rml::Matrix4f m_correction_matrix;
We don't need to keep this around as a variable. It is cleaner to just apply it directly to the projection matrix when that is constructed.

2022-06-28 14:05 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +	while (this->m_queue_pending_for_deletion_textures.empty() == false)
The queues (both for textures and geometry) might just as well be vectors. We don't need iterator or reference stability. Then, rather than changing the size on each iteration we can iterate using a range for loop and then clear the vector here.

2022-06-28 14:09 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.h
>  	Rml::Vector<PhysicalDeviceWrapper> m_physical_devices;
There are a lot of vectors here for things that we have a fixed count of. Might as well replace them with single objects or Rml::Array.

2022-06-28 14:19 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +			delete p_texture;
The problem is not all textures are destroyed when we reach the Destroy_Textures method. For that case I accumulate all pointers of handles and thus destroy those who has VmaAllocation.

Like of course ReleaseTexture method calls when we exit the application but not all textures are released. You can remove the for loop code and see the results. You can run invaders example and catch the error.

2022-06-28 14:20 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
> +	Rml::Matrix4f m_correction_matrix;
I store the variable in order to not construct the object on stack everytime when we go into the method.

2022-06-28 14:21 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
>  	Rml::Vector<PhysicalDeviceWrapper> m_physical_devices;
It was a lazy moment, but I will replace a such objects.

2022-06-28 14:58 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.h
> +	Rml::Matrix4f m_correction_matrix;
I mean you should incorporate the "correction matrix" directly _into_ the projection matrix. That one is only re-generated whenever the viewport is changed so creating it on the stack is not a problem. That way we only need one matrix multiplication whenever the transform changes.

2022-06-29 07:07 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
> +	Rml::Matrix4f m_correction_matrix;
I removed the variable from class

2022-06-29 07:08 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
>  	Rml::Vector<PhysicalDeviceWrapper> m_physical_devices;
> There are a lot of vectors here for things that we have a fixed count of. Might as well replace them with single objects or Rml::Array.

Vulkan is dynamic and all things in class are dynamic. You can't know the count of swapchain images, the semaphore count and etc, there's no point for creating Rml::Array, and the size of Vector will not resize at all. I can change the local vectors that can be arrays because you know the size and the amount of it.

If you mean local variables I will fix.

2022-06-29 07:27 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +			delete p_texture;
Removed queues, but invaders bug exists. If you know how to fix it without storing all pointers and what I did with for loop in code I would like to hear the suggestions.

ReleaseTexture doesn't accumulate all used textures in session, that's the problem. I left it as is. 
![image](https://user-images.githubusercontent.com/68504048/176376786-adb851e1-8d1a-4ab7-bc0c-45e5e24ecb25.png)
![image](https://user-images.githubusercontent.com/68504048/176376888-ab29ffe4-426a-4064-a5e0-79aa2675f759.png)

2022-06-29 07:30 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +	(pUserData);
Done.

2022-06-29 07:30 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +	while (this->m_queue_pending_for_deletion_textures.empty() == false)
Replaced with vector.

2022-06-29 07:33 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
>  	Rml::Vector<PhysicalDeviceWrapper> m_physical_devices;
Most vector construct with dynamic variables, I replaced only a little those who could be replaced with Rml::Array.

2022-06-29 11:20 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +	(pUserData);
Looks good!

2022-06-29 11:24 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.h
> +	Rml::Matrix4f m_correction_matrix;
This is being constructed in SetTransform now which is not necessary. As mentioned previously, this should be created and merged with the projection matrix, at line 2205.

2022-06-29 11:25 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +	while (this->m_queue_pending_for_deletion_textures.empty() == false)
Great!

2022-06-29 11:40 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.h
>  	Rml::Vector<PhysicalDeviceWrapper> m_physical_devices;
Yeah, I see that most of these things are dynamic in nature so that is fine. I did notice previously that we only support a single physical device, so we might as well use a single object instead of a vector for that one at least.

Another question is do we actually need to store all of them throughout the lifetime of the renderer? I think several of them are only used during initialization. In those cases they should be put as stack objects and passed as arguments where they are needed. Generally we should try to achieve the shortest possible lifetime for all objects, this makes it easier to follow the code due to the reduced number of possible states for the class.

2022-06-29 11:52 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
> +	Rml::Matrix4f m_correction_matrix;
@mikke89 Sorry! I misunderstood, okay, moved higher a bit.

2022-06-29 12:04 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
>  	Rml::Vector<PhysicalDeviceWrapper> m_physical_devices;
@mikke89 it is created as a possible deep developed API for user. Like he wants to use already set of features and don't want to implement from scratch anything, all is prepared and ready, just change some lines and you will see the results. Of course, we can minimize some things (but not all, they are required for existence) but personally there's no reason, because it will cause hard understanding of Vulkan, and some things will not be obvious especially if we reduce methods in count.

Vulkan is hard to understand for most of users, lack of tutorials, lack of any sane information, and my aim was to write in the most clearest form of renderer. I split many method, I write really many lines but follow them the user understands the action.

And why do you concern about class and his fields? It is not the real thing to be worry about, tbh, some vectors we can remove, but they are really small in count, like two??? three?? It will not change anything, because their size is small and will be really small always. 

We have things worse than Rml::Vector with 5 elements stored for the whole lifecycle of application...

2022-06-29 12:39 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.h
> +	Rml::Matrix4f m_correction_matrix;
Nice, looks good now!

2022-06-29 12:52 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
>  	Rml::Vector<PhysicalDeviceWrapper> m_physical_devices;
@mikke89 I agree with that statement, but for now it is better to keep things as they go. Also there's not so many global variables, like one and that is in class. Anyway, vulkan requires really many code and put all code in Initialize and Shutdown will break the eyes of the reader. He can have some interest in some functions for this case he goes for those functions and read them and read their scopes. But if you remove them and put in one place it provokes reader to read the whole scope while he could find only one place in that scope for the same situation it goes for methods he can analyze, and understand, and after he will go to the specific place, but he knows where it is. Changing one large scope and maintain it really hard while you can change some method that exists as a part of that (large scope) method.

If you see the clear view or clear state of class and its architecture you can refactor the code when the pull request is accepted, because for now it is just arguing about colors, what color anyone likes here. I like red with white you like green with light yellow (for example), there are many combinations, variants of how you can implement, design your class and those methods, I choose (some kind of) naive implementation, but keep all things obvious for newbies.

I completely hand over the right to you to refactor, if you really have a complete picture of what you want, and whether it will really give what you want, and whether it will give what users expect, especially users who haven't worked with Vulkan properly.

For any reasonable argument here I will answer, but now it is discussion of subjective things.

2022-06-29 19:38 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +			delete p_texture;
We need to find a fix for this, we can't work around a bug like that.

This is the validation error I'm getting:
`Cannot call vkDestroyImage on VkImage 0x4288660000026af1[] that is currently in use by a command buffer.`

So the texture is still bound, sounds to me like it is a matter of unbinding everything at the end of the frame? Then it should be free to be released during the release call at the beginning of the next frame.

2022-06-29 19:49 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.h
>  	Rml::Vector<PhysicalDeviceWrapper> m_physical_devices;
I'm not saying you should put it all in one large scope, quite the contrary! In brief, I'm saying we should reduce the excessive class variables and move them to function scope where possible. I'm not saying here that we need to reduce the number of functions.

I would argue that there are guidelines and architectural decisions that result in cleaner code, so I don't agree that it boils down to something purely subjective like a color preference. This is a pretty large class so I believe it justifies having a discussion to try to arrive at a result which is easy to reason about and maintain.

2022-06-30 07:12 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
>  	Rml::Vector<PhysicalDeviceWrapper> m_physical_devices;
@mikke89 

Still it is about refactoring and I don't know with what I can help here. I don't think we can move all things out of class or maximize their count for reducing. 

Because all things working (when we close the first review and test all things carefully again) and you just can rewrite something, try to move out, but I am doubt that it will give something useful.

2022-06-30 07:14 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +			delete p_texture;
@mikke89 

About validation error I will investigate and try to solve it, but about destroying all textures it is the bug out of system. Because ReleaseTexture doesn't accumulate all stuff when we exit from application. It is like your side.

2022-06-30 07:53 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +			delete p_texture;
@mikke89 

Also I have another question, did you investigate the problem with accumulating texture on exit from application? Because as you can see (the message with screenshots) one texture is not destroyed and for that I stored them in that m_textures field.

2022-06-30 07:59 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
>  	Rml::Vector<PhysicalDeviceWrapper> m_physical_devices;
@mikke89 

I looked again on all fields in class and I say that all things needed for working. I used Rml::Vector, because they are dynamic instances and their size can't be predicted because all machines are different and we can't know what the size will be. You can check on your own and you will understand that you will not reduce for removing them from class. just a little.

2022-06-30 10:02 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +			delete p_texture;
@mikke89 

So the renderer shouldn't accumulate all textures and it goes on user side for handling them? If so I will delete that for loop code in Destroy_Textures as you wanted.

For any other cases like this you will recieve the appropriate error message that signals about something wrong. 

I agree that discussion about rendering improvements are out of scope here, but I just did a little reminder. 

About syncronization, hard to say, it is the order of callings and probably it is about user side (how you implement that) not the API side. So it is about two things fences and semaphores, but semaphores are more about GPU->GPU talking. And the interesting part is that we have sync between CPU and GPU and it is fences, they're used, for that case I don't know why it is not syncronized well.

2022-06-30 10:41 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +			delete p_texture;
@mikke89 

Test again and confirm that you don't get the validation error with destroying.

2022-06-30 20:27 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +			delete p_texture;
I tested things now and everything seems to be working, good job :)

2022-07-01 08:47 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +			delete p_texture;
@mikke89 Hi! I hope you have powers for testings)))) 

Sorry, I was tired and didn't think well yesteday. We have to accumulate resources that attached to frames. I created the thing and test all examples again, now we have triple buffering and achieve the best performance, also I fixed some validation errros that didn't show up when it was called by Rml::Log::Message (my suggestion is to provide the logging into IDE log window like what I did for Windows), because it doesn't provide any information (I mean it consturcts the string but doesn't return anything if we say like we don't want to implement native logging in this static function).

I just forgot about that thing and my bad. Now everything should work fine as it was.

Now we don't have any errors and all are good now.

2022-07-01 11:18 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +			delete p_texture;
Nice, that looks better indeed. I didn't encounter any validation errors in my testing.

2022-07-15 14:37 UTC, mikke89 requested changes
Thanks for your continued work on this. Rendering seems to be working well when I test here locally, well done!

I have some comments that I believe could lead to improvements.

A main issue here is all the changes made to the core library, which generally should not be needed when making a new renderer. I believe all of the changes can be solved locally in the Vulkan renderer, see the individual comments for suggestions. The formatting changes made to core library files would also be very confusing for the git history. Thus, I suggest that all of the changes to the core library, as well as the other renderers, are reversed.

Generally, I still think there is too much class state in the Vulkan renderer. A lot of that can quite easily be removed, e.g. many variables are only used during initialization. I would suggest to go through the renderer carefully and clean things up where you can.

I also updated the CI so that the Vulkan renderer is tested by clang as well.

Things are getting closer to complete, keep up the good work!

2022-07-15 14:37 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +		return;
The `m_is_can_render` variable feels a bit hacky to me. Can't we instead just ensure that we don't call any rendering functions from the backend?

2022-07-15 15:04 UTC, wh1t3lord commented on Backends/RmlUi_Vulkan/ShadersCompiledSPV.h
> +static const unsigned char shader_frag_color[] = {
> Why are the alignas removed? I added these since Vulkan requires a specific alignment of the shader data, so we need to ensure the correct alignment here.

Oh sorry, I was tired when I did these commit and didn't think about it, I got annoying warning about that qualifier from cmake (CI side) and it didn't work with ignore the warning, so if you know how to fix with keeping alignas just notify me.

2022-07-15 15:15 UTC, wh1t3lord commented on Include/RmlUi/Core/Debug.h
> +	#define RMLUI_ASSERTMSG(x, m) static_cast<void>(x)
Okay I will fix this review first.

2022-07-15 21:40 UTC, mikke89 commented on Backends/RmlUi_Vulkan/ShadersCompiledSPV.h
> +static const unsigned char shader_frag_color[] = {
I see, it seems like the alignas keyword should have been placed first, I pushed an update for this specific issue.

2022-07-18 07:28 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +
done

2022-07-18 07:31 UTC, wh1t3lord commented on Backends/RmlUi_Vulkan/spirv_reflect.cpp
> +
done, but I don't want to revert in Github it is hard to do, so I just change the files. Also there's nothing wrong to get a formatted file by clang, because at some point you will format that file or files by yourself accidentally, so it is kinda fine (otherwise why do you use .clang-format if you don't apply to all files???).

2022-07-18 07:38 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
> +	#pragma GCC diagnostic ignored "-Wignored-qualifiers"
It will be hard to read and fix, so I left as is, and on practice it is really easy to add one line instead of having a really large string. So if you want you can change on your own.

2022-07-18 07:39 UTC, wh1t3lord commented on Samples/invaders/src/Game.cpp
> +	texture.Set("invaders/data/invaders.tga");
I insert your changes into these files, so they are equal. Nothing will be in merging.

2022-07-18 07:47 UTC, wh1t3lord commented on Include/RmlUi/Core/Debug.h
> +	#define RMLUI_ASSERTMSG(x, m) static_cast<void>(x)
done

2022-07-18 07:57 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +		return;
Probably it is better instead of calling from outside. I mean we don't change the architecture of callings and how the system is described for working. It is important, because just imagine that Vulkan requires to handle the drawing when we need to know resizing or minimize the window and all drawing functions and begin end frame methods we need to handle like 

if (render_interface->IsCanWeDraw()) {
  render_interface->RenderCompiledGeometry() or render_interface->RenderGeometry() and etc
}

So I don't think we should move variable in outside.

2022-07-18 08:01 UTC, wh1t3lord commented on Include/RmlUi/Core/RenderInterface.h
> +	virtual void OnWindowShown(void) = 0;
done

2022-07-18 08:01 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_GL2.cpp
> +void RenderInterface_GL2::OnWindowShown(void) {}
done

2022-07-18 08:03 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
> +	#pragma GCC diagnostic ignored "-Wignored-qualifiers"
But I recommend to create some preprocessor like RMLUI_DISABLE_ALL_COMPILER_WARNINGS_PUSH and RMLUI_DISABLE_ALL_COMPILER_WARNINGS_POP in order to unify all pragmas in order to do that use _Pragma("clang diagnostic push") and other strings to implement for MSVC, GCC and clang compilers respectively.

2022-07-19 07:15 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +		return;
Because you have callings like RenderCompiledGeometry and just RenderGeometry from different places and it is not right!!!!!! if you want to have a thing like move variable outside, no, it will not work like that, so I suppose to leave it as is without any changes, because it is private data and we have all needed callbacks for resolving rendering.

2022-07-20 18:06 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.h
> +	#pragma GCC diagnostic ignored "-Wignored-qualifiers"
If you instead want to use this approach with _Pragma that's perfectly fine with me so feel free to do that, however only locally in the Vulkan renderer where this is needed.

2022-07-20 18:09 UTC, mikke89 commented on Samples/invaders/src/Game.cpp
> +	texture.Set("invaders/data/invaders.tga");
They are not equal as you can see from `git diff master --stat -- Samples/`. This will cause merge conflicts, so please revert them properly, this includes all formatting changes as well.

2022-07-20 18:09 UTC, mikke89 commented on Backends/RmlUi_Renderer_GL2.cpp
> +void RenderInterface_GL2::OnWindowShown(void) {}
Great!

2022-07-20 18:14 UTC, mikke89 commented on Backends/RmlUi_Vulkan/spirv_reflect.cpp
> +
We don't format all our files because that would ruin a lot of git history. This was decided back when we introduced .clang-format. We only format new code.

Formatting code not related to your current changes makes it hard to see what is actually new and what is just formatting changes. So please revert the files properly.

2022-07-20 18:24 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +		return;
I mean, we can just not call Context::Render from the backend, this way we don't have any calls to e.g. RenderCompiledGeometry either so we don't need that bool guard inside the class. No changes needed to the core library.

2022-07-21 09:26 UTC, wh1t3lord commented on Samples/invaders/src/Game.cpp
> +	texture.Set("invaders/data/invaders.tga");
Hi, I will try to revert.

2022-07-21 09:39 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +		return;
I described an idea, give some feedback please.

2022-07-21 10:16 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
> +	#pragma GCC diagnostic ignored "-Wignored-qualifiers"
done

2022-07-24 18:36 UTC, mikke89 commented on Backends/RmlUi_Renderer_Vulkan.h
> +	#pragma GCC diagnostic ignored "-Wignored-qualifiers"
Hey, it looks fine, but as I mentioned please don't modify the core files but add this to the Vulkan renderer only, as they are currently only needed there. Also, you could use the new macro instead of listing the warnings in `RmlUi_Renderer_Vulkan.cpp` as well.

2022-07-25 07:48 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.h
> +	#pragma GCC diagnostic ignored "-Wignored-qualifiers"
done

2022-07-25 08:23 UTC, wh1t3lord commented on Samples/invaders/src/Game.cpp
> +	texture.Set("invaders/data/invaders.tga");
done

2022-07-25 09:34 UTC, wh1t3lord commented on Backends/RmlUi_Vulkan/spirv_reflect.cpp
> +
I guess you can close this thing, if you know any other uncheckouted files tell me please. 

So I will say that this review is completed.

2022-07-26 13:14 UTC, wh1t3lord commented on Backends/RmlUi_Vulkan/spirv_reflect.cpp
> +
done

2022-07-26 13:14 UTC, wh1t3lord commented on Samples/invaders/src/Game.cpp
> +	texture.Set("invaders/data/invaders.tga");
done

2022-07-26 13:27 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +		return;
Anyway I left this functionality I mean the raw (not virtual) methods for Vulkan class, because we can't know what would come in future. And for user we just gave an idea how he can implement things. But what I did to prevent the rendering is to store in context the flag when window is minimized flag set to true otherwise it is false. When the flag is false we can do some work of our application.

This is the last review and I hope we are good here and can proceed to merging this stuff and I would really happy if it goes to some releases.

2022-07-26 13:27 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +		return;
done

2022-07-26 13:29 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +		return;
Probably it is better to rename the method like IsWindowValid and it means it is not minimized and it is not hidden. Because now it takes only minimized state into account.

2022-08-05 09:52 UTC, wh1t3lord commented on Backends/RmlUi_Renderer_Vulkan.cpp
> +		return;
Done

2022-08-17 09:17 UTC, mikke89 approved these changes

2022-08-17 09:24 UTC, mikke89 commented
Great work, thanks again! Appreciate all the effort that went into this.

I'm merging it into the vulkan branch to polish it up a bit before eventually merging it to master.

2022-08-17 09:30 UTC, merged